### ISSUE TITLE
[functions]
  directory = "my_functions"


### ISSUE THREAD

**Issue by lemurcina** [wbyoung/avn#117]
Need to fix this.

**Comment by wbyoung** [comment]
I'm not sure what you mean with this.

Also, just FYI: I'm personally not using this project any more (and not really coding). I'm happy to review and accept a PR that fixes an issue, though.

**Comment by lemurcina** [comment]
Thanks a lot.

**Comment by wbyoung** [comment]
Not enough details at this point. PR welcome.
