### ISSUE TITLE
avn-nvm: nvm exited with status: 127

### ISSUE THREAD

**Issue by crucialfelix** [wbyoung/avn#14]
Hi, not quite sure what failed here.

```shell
Sites ❯ mattermind-site
Gemfile          Makefile         bower.json       config.rb        gulpfile.js      off              scrap            work
Gemfile.lock     README.md        bower_components dist             node_modules     package.json     src
avn could not activate node v0.10.32
mattermind-site ❯ _avn explain -v .
avn could not activate node v0.10.32
error: no plugin passed predicate
  avn-nvm: nvm exited with status: 127
  avn-n: no version matching v0.10.32
mattermind-site ❯ nvm list
    iojs-v1.3.0
    iojs-v2.0.0
       v0.10.32
->       system
node -> v0.10.32
stable -> 0.10 (-> v0.10.32) (default)
```

It would appear that nvm has v0.10.32 but maybe its being invoked wrong.

avn: 0.1.7
avn-nvm: 0.1.5

thanks

**Comment by ljharb** [comment]
fwiw, `nvm` only exits with `127` explicitly on install or uninstall, when `nvm install` without a version being specified and without an `.nvmrc` file present somewhere.

**Comment by wbyoung** [comment]
@crucialfelix I believe this is an error with the `nvm` command not being found by the plugin. I added a little more detail to the error message that's being shown. Can you update `avn-nvm` via an install from the repo:

```bash
rm -r ~/.avn/plugins/avn-nvm
npm i -g wbyoung/avn-nvm
avn setup
```

Try running it again and let me know what error message you get.

Also, a few questions that could help track this down:

- What do you get if you run `bash -c 'source $NVM_DIR/nvm.sh; nvm ls'`?
- What shell are you using?
- What OS are you on?
- Is your `nvm` setup customized at all?
- What is the node version that you start with (your nvm system version)? `node --version`

**Comment by crucialfelix** [comment]
I'm on zsh, OS X

Indeed, bash is not able to find nvm

```shell
materialize ❯ bash -c 'source $NVM_DIR/nvm.sh; nvm ls'
bash: /nvm.sh: No such file or directory
bash: nvm: command not found

materialize ❯ node --version                                                                                                                                                                          
v0.12.0
```

I should probably use brew to install .nvm
It looks like I git cloned it myself (?)

thanks, I'll report more later when I have a chance.

**Comment by ljharb** [comment]
Please do **not** use brew to install `nvm` - brew is completely unsupported. Use the `curl` command in the README: `curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.25.4/install.sh | bash`

**Comment by wbyoung** [comment]
Oh, I forgot to ask for the `nvm --version` as well.

It looks like `NVM_DIR` is not part of your `env`. Can you confirm by seeing if `env | grep NVM_DIR` produces anything?  

Does your `~/.zshrc` contain a line that looks like any of these:

```sh
# option A
[[ -s $HOME/.nvm/nvm.sh ]] && . $HOME/.nvm/nvm.sh # This loads NVM

# option B
export NVM_DIR="/Users/wbyoung/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh" # This loads nvm

# option C
. ~/.nvm/nvm.sh
```

If not, how is `nvm` being loaded?

Do you have any other startup configuration files with `nvm` setup in them? `~/.bash_profile`, `~/.bashrc`, `~/.zshrc` or `~/.profile`

**Comment by crucialfelix** [comment]
Works now.

```
avn using node v0.10.32 (avn-nvm v0.10.32)
```

I had this in `~/.bash_profile`
```
NVM_DIR=~/.nvm
source ~/.nvm/nvm.sh
```

but what fixed it was to make a `~/.bashrc`
```
export NVM_DIR=~/.nvm
source $NVM_DIR/nvm.sh
```

actually its probably just the missing export in .bash_profile

I source that in my `~/.zshrc`

For error checking if you could inform us if $NVM_DIR is unset that would help.

thanks !

**Comment by wbyoung** [comment]
@crucialfelix yes, it was the missing `export`.

If you even just had `source ~/.nvm/nvm.sh`, then the `nvm` script would have exported `NVM_DIR` for you. The improved error message that I just added to track this down with you should help others in the future since `avn` will now report `bash: /nvm.sh: No such file or directory` when attempting to run an `nvm` command.

Glad we got it working for you. :)

**Comment by WendyMcF** [comment]
Changing my .bash_profile from
`NVM_DIR=~/.nvm`
`source ~/.nvm/nvm.sh`
to
`export NVM_DIR=~/.nvm`
`source ~/.nvm/nvm.sh`
solved 
`avn could not activate node 0.12.7`
for me too.
