### ISSUE TITLE
Not resolving the version

### ISSUE THREAD

**Issue by tregusti** [wbyoung/avn#15]
Hi, I have an issue where avn can't load the corrent version of node even though it is installed.

This is how it looks for me:

![](https://dl.dropboxusercontent.com/s/ck1mhr1ju4iu0g7/2015-06-04%20at%2012.21.png?dl=0)

I've tried with and without `v` prefix. And I know that has worked fine before. Also, just before creating the test here, I reinstalled `avn` and `avn-nvm`.

Any ideas what I should try?

**Comment by wbyoung** [comment]
Can you include [the output of `_avn explain -v .`](https://github.com/wbyoung/avn#troubleshooting) please?

**Comment by tregusti** [comment]
Sure:

```
avn could not activate node 0.10.33
error: no plugin passed predicate
  avn-nvm: Invalid Version: iojs-v1.4.3
```

I'm not using iojs here, so I don't understand the relevance of the error.

**Comment by wbyoung** [comment]
Try updating:

npm i -g avn avn-nvm
avn setup

If that doesn't work, can you update to master & do another explain:

rm -r ~/.avn/plugins/avn-nvm
npm i -g wbyoung/avn-nvm
avn setup

Also, can you provide the output to `nvm list` if things don't work.

**Comment by tregusti** [comment]
Ok, sorry for taking you time. My bad. I was testing back and forth with different versions of node. And of course I had an different version of avn installed in the different versions of node I was testing in. I updated in all versions and now it works just fine...

Again. sorry. Close at will.

**Comment by wbyoung** [comment]
No worries. Glad you got it sorted out. If you can think of any way `avn` could have helped discover the cause of this error, feel free to open a new issue with suggestions on error output (or a pull request).
