### ISSUE TITLE
Opening new tmux split runs avn twice

### ISSUE THREAD

**Issue by aaronjensen** [wbyoung/avn#20]
Using zsh, these dotfiles: https://github.com/aaronjensen/dotfiles

When I open a tmux split from a directory w/ a .nvmrc I get two activation messages. The first is in color, the second is not:

```
avn activated v0.10.26 via .nvmrc (avn-nvm v0.10.26)
avn activated v0.10.26 via .nvmrc (avn-nvm v0.10.26)
```

To repro, use my dotfiles:

```
$ tmux
$ cd <some dir w/ .nvmrc>
# Hit ctrl-o, v to open a split
```

**Comment by wbyoung** [comment]
@aaronjensen thanks for the report.

I can't reproduce this, but I'm also needing to comment out `set-option -g default-command "reattach-to-user-namespace -l $SHELL -l"` from your tmux config to get tmux running. Perhaps that could be the problem… can you try disabling this and see what happens?

I'll try to look into this more at some point, but the duplicate message is probably a symptom of `avn` receiving multiple calls for the `chpwd_functions` hook or being run multiple times. Also, your setup probably puts you into an _edge case_ category, so while I'd like to get to the bottom of this, it's also likely that it'll be a low priority.

PR welcome, though. :smile:

**Comment by aaronjensen** [comment]
Removing `reattach-to-user-namespace` doesn't help. When you used the were you using bash or zsh? They start out as zsh by default.

I just added a .nvmrc to my home directory and opened a new window and it repro'd, so no tmux required...

**Comment by aaronjensen** [comment]
Here's the problem, a hack to work around problems w/ rvm: 

https://github.com/aaronjensen/dotfiles/blob/master/zlogin#L2

so... i guess it'd be nice if avn was idempotent. It didn't switch versions if it didn't need to?

**Comment by aaronjensen** [comment]
I fixed the root cause (zshenv adding to path multiple times somehow broke rvm's initial path loading) and removed the hacks. All good now. It'd still be nice if avn was idempotent (especially because avn, and to a lesser extent nvm, is surprisingly slow)

**Comment by wbyoung** [comment]
It's

**Comment by wbyoung** [comment]
It's idempotent with respect to itself, but it'd require (more) internal knowledge of nvm and n to truly get there.

**Comment by wbyoung** [comment]
Oh, and on the speed issue: avn should not have any noticeable impact when you cd anywhere without a config file.

When it performs a switch, it may be slow (it starts a node process & performs file operations), but as you mention nvm can be slow, too. I could add some profiling timers into the code base to help figure out where speed issues occur. I've had better luck with n for faster startup of new shells and switching.

I know @ljharb and others have been working on speed in nvm:

https://github.com/creationix/nvm/issues/703
