### ISSUE TITLE
Permission Denied Errors

### ISSUE THREAD

**Issue by kevinswarner** [wbyoung/avn#23]
OSX Yosimite 10.10.5
n
avn

When avn switches versions of node, I get the following errors...

/usr/local/bin/n: line 254: /usr/local/n/versions/.prev: Permission denied
cp: /usr/local/lib/dtrace/node.d: Permission denied
cp: /usr/local/lib/node_modules/npm/.npmignore: Permission denied
cp: /usr/local/lib/node_modules/npm/.npmrc: Permission denied
cp: /usr/local/lib/node_modules/npm/.travis.yml: Permission denied
... AND LOTS MORE ...

NOTE: It appears the node version is switched (e.g. node --version prints out correct version)

But, I am not confident because of these errors.

When installing anything globally, I have to use sudo (always have had to on my mac). So, n and avn were installed using sudo.

I get this same issue when running n without sudo. So, I believe if I could have avn run n using sudo, this would solve the issue.

Is there a way to have avn run n as sudo? Or, is there a different approach I should be taking here?

**Comment by wbyoung** [comment]
@kevinswarner you should change your setup so you don't have to use `sudo` to run `n`. This likely can be done with something like:

```bash
sudo chown -R  `whoami` $N_PREFIX
```

This is not something that will be changed in `avn`, though.
