### ISSUE TITLE
Could not active node: nvm.sh missing and found under /usr/share/nvm/

### ISSUE THREAD

**Issue by juhamust** [wbyoung/avn#27]
After getting this issue and finding the root cause, I though about sharing it here, too. Perhaps the code / logging / documentation could be improved based on it.

As it can be seen, the avn failed to active the correct node even if the `avn setup` and shell restart were run succesfully. The reason was missing nvm.sh file under home directory.
```shell
> avn could not activate node v0.12.7

> __avn_debug      
avn could not activate node v0.12.7
error: no plugin passed predicate
  avn-nvm: nvm exited with status: 127
zsh:source:1: no such file or directory: /home/juha/.nvm/nvm.sh
zsh:1: command not found: nvm

> ls -l ~/.nvm
total 0
drwxr-xr-x 1 juha juha 14 syys  16 22:23 alias
drwxr-xr-x 1 juha juha 44 syys  16 20:43 bin
drwxr-xr-x 1 juha juha  8 syys  16 20:44 versions

> whereis nvm
nvm: /usr/share/nvm

> ls -l /usr/share/nvm 
total 72
-rw-r--r-- 1 root root  1846 syys  28 20:43 bash_completion
-rw-r--r-- 1 root root    95 syys  28 20:43 init-nvm.sh
-rw-r--r-- 1 root root 62737 syys  28 20:43 nvm.sh

ln -s /usr/share/nvm/nvm.sh /home/juha/.nvm/nvm.sh
```

After linking the file the activation worked.

The nvm was installed via Arch Linux AUR, so it could be the reason, I don't know?

**Comment by ljharb** [comment]
As the maintainer of `nvm`, the only supported way to install it is via the `curl` command in the README at http://nvm.sh. If you install it that way, does it work?

Note also that there shouldn't be a "bin" directory, so you may have installed the wrong `nvm`.

**Comment by juhamust** [comment]
Understood. I removed old `.nvm` folders and nvm initializations from `.zshrc`, but installation keeps jamming on following:

```
22:52:26 juha@zbox ~ curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.27.1/install.sh | bash          130 ↵
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  7731  100  7731    0     0  18762      0 --:--:-- --:--:-- --:--:-- 18810
=> Downloading nvm from git to '/home/juha/.nvm'
=> Cloning into '/home/juha/.nvm'...
remote: Counting objects: 3973, done.
remote: Compressing objects: 100% (45/45), done.
remote: Total 3973 (delta 25), reused 1 (delta 1), pack-reused 3927
Receiving objects: 100% (3973/3973), 984.64 KiB | 1.03 MiB/s, done.
Resolving deltas: 100% (2305/2305), done.
Checking connectivity... done.
* (HEAD detached at v0.27.1)
  master

=> Appending source string to /home/juha/.zshrc
```
And nothing happens since.

**Comment by gaboesquivel** [comment]
that's the last installation step https://github.com/creationix/nvm/blob/master/install.sh#L242 
you just need to make sure it properly sourced in your .zshrc and then restart your shell or reload configs
you need to source both avn and nvm 

```
exports HOME=/home/juha/
[[ -s $HOME/.nvm/nvm.sh ]] && $HOME/.nvm/nvm.sh # This loads NVM
[[ -s "$HOME/.avn/bin/avn.sh" ]] && source "$HOME/.avn/bin/avn.sh" # load avn
```

**Comment by wbyoung** [comment]
@juhamust as @gaboesquivel said, it seems like you're all set up now.

If you're still having issues, please let us know what your `.zshrc` looks like as well as what `__avn_debug` is reporting now.

If all is working, feel free to close this issue.

**Comment by juhamust** [comment]
No issues - just some findings that I thought about sharing (maybe someone will find them useful). 

As for the curl based installation, I would have expect it to stop instead of just "stopping" there with the last line.
