### ISSUE TITLE
Hangs forever on cd or __avn_debug

### ISSUE THREAD

**Issue by nevir** [wbyoung/avn#33]
Unfortunately, I'm not sure what other information I can provide.

I'm running zsh (oh-my-zsh)

The steps I took:

1. `curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.29.0/install.sh | bash` (reopen terminal)
2. `nvm install 4.2.3`
3. `nvm alias default 4.2.3` (`avn` explodes if there isn't a `node` on the path)
4. `npm install -g avn avn-nvm`
5. `avn setup` (reopen terminal)
6. Add a `.node-version` with 4.2.3 to a directory
7. cd into that directory. avn hangs forever.

**Comment by nevir** [comment]
Ah!  ok, so it turns out I somehow had

    [[ -s "$HOME/.avn/bin/avn.sh" ]] && source "$HOME/.avn/bin/avn.sh" # load avn

present in **both** `.zshrc` and `.zshenv`.

**Comment by wbyoung** [comment]
Glad you figured it out. `avn` doesn't write to `.zshenv`, so I'm not sure how it got there. Perhaps another setup script copied it there?
