### ISSUE TITLE
suggestion: follow XDG base directory spec

### ISSUE THREAD

**Issue by davidosomething** [wbyoung/avn#34]
instead of polluting home, provide env vars for avn like AVN_CONFIG_DIR or something and look in ~/.config/avn if .avn is not found in home folder

**Comment by wbyoung** [comment]
Happy to accept a PR for the environment variable for an install location, but without a compelling reason to move the install by default, I don't want to. Polluting the home dir isn't a concern to me, and for those who care, the environment variable should be sufficient.

**Comment by wbyoung** [comment]
I'm going to close this as it's not an actual bug, but will be happy to continue discussion and/or review a PR. Thanks for the suggestion!
