### ISSUE TITLE
__avn_debug command not found

### ISSUE THREAD

**Issue by grssnbchr** [wbyoung/avn#40]
I get a "command not found" error when trying to run __avn_debug or _avn in the shell. 
I installed via "npm i -g avn avn-nvm" and successfully ran "avn setup".

**Comment by wbyoung** [comment]
What shell and what version are you using? What does your profile (`~/.{bash|zsh}{_profile|rc}`) look like for that shell? Did you launch a new shell after running `avn seup` or just continue to use the same shell? Can you try launching a new shell?

Also, [anything here](https://github.com/wbyoung/avn/blob/master/ISSUE_TEMPLATE.md) that you can provide would help.

**Comment by grssnbchr** [comment]
* Shell: bin/bash
* avn 0.2.3
* node 4.0.0 / 0.12.1, depending on my nvm setup
* nvm 0.31.0

* avn is loaded in my ~/.{bash|zsh}{_profile|rc} file with:
`[[ -s "$HOME/.avn/bin/avn.sh" ]] && source "$HOME/.avn/bin/avn.sh" # load avn`

* there is nothing avn-related in .bashrc

I basically installend avn with `npm install -g avn avn-nvm` with both of my node versions (v4.0.0 and v0.12.1) and ran `avn setup` for both. Opening up a new shell doesn't solve the problem. 

Thank you

**Comment by wbyoung** [comment]
What happens when you source it directly with `source "$HOME/.avn/bin/avn.sh"`?

**Comment by grssnbchr** [comment]
Now it works - I added `source "$HOME/.avn/bin/avn.sh"` to my `.bashrc`. Somehow, `.bash_profile` is not recognized in my system (and redundant, anyway, because I have `.bashrc`). Maybe `avn` should check for the existence of `.bashrc` upon setup. Thanks!

**Comment by wbyoung** [comment]
Yup, it's hard to get right. See #31.

**Comment by edsfocci** [comment]
@grssnbchr What operating system were you running at the time (March 25, 2016), including version number? I'm guessing probably not one based on Ubuntu 16.04, unless you were running a beta or release candidate OS.

**Comment by grssnbchr** [comment]
@edsfocci Ubuntu 12.04
