### ISSUE TITLE
Proper instructions to remove avn from my system

### ISSUE THREAD

**Issue by lesterzone** [wbyoung/avn#42]
Is there a section / docs about how to remove avn from my system?
`npm uninstall avn avn-nvm` and removed ~/.avn and ~/.avnrc but still get this `_avn: command not found`
edited my ~/.bashrc and source it

**Comment by wbyoung** [comment]
You'll need to launch another shell after. There's no un-source functionality for shells. But you got it all.

**Comment by lesterzone** [comment]
Thanks.
