### ISSUE TITLE
AVN on windows?

### ISSUE THREAD

**Issue by tehandyb** [wbyoung/avn#46]
Does AVN work on windows? There is a nvm-windows library, but I wasn't sure if the avn-nvm would work with that.

**Comment by wbyoung** [comment]
I'm not sure. Because I don't personally use Windows, I won't add the support for it, but fully welcome any PR that adds support. Please include tests & Travis CI test integration.

I'm going to close this as its not an issue that is necessary to track, but anyone who wants to work on it can open a PR.

**Comment by tehandyb** [comment]
Where should I start if I wanted to contribute? I was looking through the code for a sec but am a bit lost as to where it uses nvm.

**Comment by wbyoung** [comment]
It's plugin based, so see [`avn-nvm`](https://github.com/wbyoung/avn-nvm).

**Comment by dominicrico** [comment]
@tehandyb and @wbyoung  I know it's a closed Issue, but if you want AVN to work on Windows and you use [CMDER](http://cmder.net/) as your console emulator you can just change one simple thing in the installer script to make it work on Windows. 

[Installer.js Line 48](https://github.com/wbyoung/avn/blob/498ee492c727839ce463b5c4c63935110bf5293f/lib/setup/install.js#L48) 

Change `var cmd = cp.spawn('/bin/cp', ['-RL', src, dst]);` to `var cmd = cp.spawn('cp', ['-RL', src, dst]);` and run `avn setup`. Done!

**Comment by dyh333** [comment]
hi, @dominicrico . I use the CMDER mini, and change the Installer.js Line 48. but when I cd to the project path, the nvm used version is not changed, do you know why? do I need to use CMDER full ? thanks

**Comment by dominicrico** [comment]
Hey @dyh333,

not sure how the full version is different to de mini version. But I don't think that this would cause the issue. Do you have a `.node-version` file in that folder?

**Comment by dyh333** [comment]
hi, @dominicrico . yes I put the .node-version file in the root folder of project, and inside text as below:
![image](https://user-images.githubusercontent.com/1221313/38362233-a676ded4-3902-11e8-9fa2-71d2f4cbf733.png)

and avn setup show me as below:
![image](https://user-images.githubusercontent.com/1221313/38362298-e4671e34-3902-11e8-83d2-554f040a74bc.png)

**Comment by dominicrico** [comment]
@dyh333 have you installed **nvm** and **avn-nvm**?

**Comment by dyh333** [comment]
@dominicrico , yes I had installed nvm and avn-nvm, using "npm install -g avn avn-nvm".  but I cannot use __avn_debug, while avn seems work
