### ISSUE TITLE
nvm aliases not recognized

### ISSUE THREAD

**Issue by duckontheweb** [wbyoung/avn#52]
Please describe your issue clearly and also include all details below.

**Details**

- _avn_ `0.2.3`
- _node_ `v7.4.0`
- _nvm_ `0.33.0`
- _n_ `n: command not found`
- _zsh_ `zsh 5.0.8 (x86_64-apple-darwin15.0)`
- _bash_ `GNU bash, version 3.2.57(1)-release (x86_64-apple-darwin15)`

The output of `__avn_debug` in the directory with a `.node-version` file is:

```sh
avn could not activate node lts/boron
error: no plugin passed predicate
  avn-nvm: no version matching lts/boron
```

`avn` is loaded in my `~/.{bash|zsh}{_profile|rc}` file with:

```sh
[[ -s "$HOME/.avn/bin/avn.sh" ]] && source "$HOME/.avn/bin/avn.sh" # load avn
```

**nvm specific**

- [ yup] As an `nvm` user I am confirming that I did _not_ install with Homebrew

I was under the impression (based on the fact that #43 had been closed) that nvm aliases like `lts/boron` were now supported by `avn` and/or `avn-nvm`. However, I have tried the following content in both a `.nvmrc` and a `.node-version` file and neither is picked up by `avn`:

```text
lts/boron

```

The alias does seem to be working correctly with `nvm`:

```bash
jduckwor$ nvm use
Found '/Users/jduckwor/WorkRelated/managed_code/mvt-platform/mvt-image-backend/.nvmrc' with version <lts/boron>
Now using node v6.9.4 (npm v3.10.10)
```

**Comment by wbyoung** [comment]
Yeah, I'll just reopen #43… more details are over there. The original requester closed it, but I'm still happy to take a PR for it.

**Comment by duckontheweb** [comment]
Thanks @wbyoung. If I have some time I'll take a look at the code and see if it's something I can contribute to.
