### ISSUE TITLE
npm version not restoring

### ISSUE THREAD

**Issue by alextrastero** [wbyoung/avn#59]
When switching from projects with different node-versions avn switches fine but my npm version doesn't switch, what am I doing wrong?

<img width="404" alt="screen shot 2017-09-13 at 12 26 35" src="https://user-images.githubusercontent.com/4152819/30372657-df312e84-987e-11e7-8ca2-48d72dde6725.png">

**Comment by ljharb** [comment]
It looks like it's switching fine in your image?

**Comment by alextrastero** [comment]
yes, node version switching fine, but npm version not persisting, I eventually switch from `n` to `nvm` and that solved it

**Comment by wbyoung** [comment]
It's also possible that you updated `npm` for that install of `node`.

**Comment by ljharb** [comment]
Right - npm comes with node, so every time you switch node versions, you're switching npm versions too. It's not *supposed* to persist.

**Comment by alextrastero** [comment]
Yes, but when you switch back to the previous project shouldn't it restore to the npm version installed with THAT node version? (like the screenshot shows) :)

**Comment by ljharb** [comment]
Ah, your screenshot wasn't clear - are you saying the node version (for which npm was v5.4.1) was 6.11.0?

**Comment by wbyoung** [comment]
I believe that `n` would have the upgrade of `npm` persist, but I haven't confirmed that.
