### ISSUE TITLE
Not actually switching

### ISSUE THREAD

**Issue by ENG618** [wbyoung/avn#61]
Please describe your issue clearly and also include all details below.

Has never worked for me.  It has only served as a warning to manually run `nvm use x.x.x`.

Whenever switching to a dir I get the `avn could not activate node x.x.x`

**Details**

- _avn_ `avn --version`: 0.2.3
- _node_ `node --version`: 8.1.3
- _nvm_ `nvm --version`: 0.33.4
- _n_ `n --version`: na
- _zsh_ `zsh --version`: zsh 5.2 (x86_64-apple-darwin16.0)
- _bash_ `bash --version`: 4.4.12(1)-release

The output of `__avn_debug` in the directory with a `.node-version` file is:

```sh
avn could not activate node 6.11.1
error: no plugin passed predicate
  avn-nvm: nvm exited with status: 127
/usr/local/bin/bash: /Users/engarcia/.nvm/nvm.sh: No such file or directory
/usr/local/bin/bash: nvm: command not found
  avn-n: no version matching 6.11.1
```

`avn` is loaded in my `~/.{bash|zsh}{_profile|rc}` file with:

```sh
[[ -s "$HOME/.avn/bin/avn.sh" ]] && source "$HOME/.avn/bin/avn.sh" # load avn
```

**nvm specific**

- [ ] As an `nvm` user I am confirming that I did _not_ install with Homebrew

**Comment by wbyoung** [comment]
Is there a file at `/Users/engarcia/.nvm/nvm.sh`?

I'd suggest trying to uninstall and reinstall `nvm`. Also, please be sure you did not install via Homebrew. If you did, things are expected to fail (hence the checkbox above asking about it).

**Comment by ENG618** [comment]
Okay, seems to be working fine now...had it installed with homebrew originally
