### ISSUE TITLE
New terminal tabs open slower after installing avn with nvm

### ISSUE THREAD

**Issue by ip** [wbyoung/avn#62]
Please describe your issue clearly and also include all details below.

**Details**

- _avn_ `avn --version`
0.2.3
- _node_ `node --version`
6.11.5
- _nvm_ `nvm --version`
0.33.6
- _n_ `n --version`
- _zsh_ `zsh --version`
zsh 5.3 (x86_64-apple-darwin17.0)
- _bash_ `bash --version`

`avn` is loaded in my `~/.{bash|zsh}{_profile|rc}` file with:

```sh
[[ -s "$HOME/.avn/bin/avn.sh" ]] && source "$HOME/.avn/bin/avn.sh" # load avn
```

**nvm specific**

- [x] As an `nvm` user I am confirming that I did _not_ install with Homebrew

**Comment by ljharb** [comment]
This is because nvm relies on `npm config get prefix`, which is slow. It’s not an issue with avn itself.

**Comment by wbyoung** [comment]
Yup, as @ljharb says. I personally use `n` for speed and because I don't actually switch node versions often (if I did, I'd prefer `nvm`'s `PATH` updating approach).
