### ISSUE TITLE
Test RegEx not catching all cases

### ISSUE THREAD

**Issue by duckontheweb** [wbyoung/avn#63]
Please describe your issue clearly and also include all details below.

**Details**

- _avn_ `0.2.3`
- _node_ `v6.11.5`
- _nvm_ `0.33.6`
- _n_ `2.0.0`
- _zsh_ `zsh 5.0.8 (x86_64-apple-darwin15.0)`
- _bash_ `version 3.2.57(1)-release (x86_64-apple-darwin15)`

The output of `__avn_debug` in the directory with a `.node-version` file is:

```sh
# paste output here
```

`avn` is loaded in my `~/.{bash|zsh}{_profile|rc}` file with:

```sh
# find the relevant line(s) in your profile & note path above
```

**nvm specific**

- [x] As an `nvm` user I am confirming that I did _not_ install with Homebrew

I am starting in on a PR for #43, but I have a couple of tests failing. One of them is the `fails for any failed action` test in `test/setup.js`, which give the following failed test output:

```bash
AssertionError: expected 'error: EACCES: permission denied, open \'/var/folders/1p/9z6dp_4n2cd27d2ktj6w_xv40000gn/T/d-1171011-15092-10e8ilz.4tsh8h0k9/.bash_profile\'\n' to match /^error: EACCES.*, open '[\/\w-]*\/.bash_profile'\n$/
```

It looks like the regex is just not catching my error message case. I can dig into the regex and fix it to catch this, but I wanted to bring this to your attention in case it's a known issue that I should ignore.

**Comment by duckontheweb** [comment]
This is the old regex:

```javascript
^error: EACCES.*, open '[\/\w-]*\/.bash_profile'\n$
```
This is the updated regex that catches my case:

```javascript
/^error: EACCES.*, open '[\/\w-\d\.]*\/.bash_profile'\n$/
```

The changes were matching digits and the dot character in the directory portion before `.bash_profile`. I've tested this locally and the test now passes.

**Comment by wbyoung** [comment]
@duckontheweb looks like a good change. Please feel free to throw up a separate PR.
