### ISSUE TITLE
avn could not activate node v0.12.0 error

### ISSUE THREAD

**Issue by jakecraige** [wbyoung/avn#7]
After installing, I'm getting this error. I ran `npm install -g avn avn-nvm` and `avn setup`. Then restarted the terminal

```
$ node -v
v0.10.36

$ cd my-project
avn could not activate node v0.12.0

$ cat .node-version
v0.12.0

$ nvm ls
    iojs-v1.0.4
->     v0.10.36
        v0.12.0
         system
default -> v0.10.36
stable -> 0.12 (-> v0.12.0) (default)
```

**Comment by ljharb** [comment]
This may be because starting with `iojs`, and version `0.12.0`, node versions are stored in a different path, nested inside `$NVM_DIR/versions/node` and not in the root of `$NVM_DIR`.

**Comment by wbyoung** [comment]
Thanks @ljharb. It was actually a problem with the assumption that `nvm list` would produce a list of versions, but `iojs-v1.1.0` is not simply a version number, so it throws errors with `semver`. See wbyoung/avn-nvm@694ae69 for the fix.

To update your installation:

```bash
npm i -g avn avn-nvm
avn setup
```

Then restart your shell.
