### ISSUE TITLE
Very simple line to add for full brew support on macOS (possible README.md add)

### ISSUE THREAD

**Issue by kickthedragon** [wbyoung/avn#83]
For `brew` to work with `avn` theres just two very simple edits you need to make to your .bash profile

when you install `nvm` via `brew` it adds these two lines to the top of your `.bash_profile`

```
NVM_DIR=~/.nvm
source $(brew --prefix nvm)/nvm.sh
```
if you export the `NVM_DIR` variable and create a symlink to the `brew` `nvm.sh` location `avn` works entirely as expected.

```
export NVM_DIR=~/.nvm
source $(brew --prefix nvm)/nvm.sh
ln -sf $(brew --prefix nvm)/nvm.sh $NVM_DIR/nvm.sh 
```

**Comment by ljharb** [comment]
nvm is explicitly not supported via homebrew; please don't encourage people to install it that way.

**Comment by wbyoung** [comment]
I understand the desire for this to work, but I don't think it's a good idea to try to support something that an upstream project doesn't support.
