### ISSUE TITLE
how does avn works

### ISSUE THREAD

**Issue by a-x-** [wbyoung/avn#93]
Could you describe how avn on dir enter mechanics works in readme?

**Comment by wbyoung** [comment]
Start by looking [here](https://github.com/wbyoung/avn/blob/master/bin/avn.sh). I don't think how it works is relevant for the readme. That type of thing is probably better for an independent blog post.

**Comment by a-x-** [comment]
Ok, I got that zsh `chpwd_functions` used

Short answer in readme might be address confidence questions, I think
